# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    name: web
  name: web-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: web
    spec:
      containers:
      - env:
        - name: SKYLIGHT_AUTHENTICATION
          valueFrom:
            secretKeyRef:
              key: skylightsecret
              name: secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgrespassword
              name: secrets
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgresuser
              name: secrets
        - name: RAILS_ENV
          value: production
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              key: railssecret
              name: secrets
        image: registry.gitlab.com/nambrot/nambrotdotcom:latest
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 3000
          name: http-server
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log

      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry.gitlab.com
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
