apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.applicationName }}-ingress
  labels:
    app: {{ .Values.slugName }}
    application: {{ .Values.applicationName }}
    environment: {{ .Values.environment }}
    tier: ingress
    resource: ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
  namespace: {{ .Values.namespace.name }}
spec:
  tls:
  - hosts:
    - {{ .Values.slugName }}.nambrot.com
    secretName: echoserver-tls
  rules:
  - host: {{ .Values.slugName }}.nambrot.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.applicationName }}-service
          servicePort: 80
