# web-service.yml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-service
  labels:
    app: {{ .Values.slugName }}
    application: {{ .Values.applicationName }}
    environment: {{ .Values.environment }}
    tier: service
    resource: service
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ .Values.slugName }}
    application: {{ .Values.applicationName }}
    environment: {{ .Values.environment }}
    tier: webapp
