# Default values for review-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image: registry.gitlab.com/nambrot/nambrotdotcom:master
namespace:
  name: fix-issue-12
environment: review
applicationName: nambrotdotcom
slugName: fix-issue-12
